name: docs-deploy
on:
  push:
    branches: [ "master", ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install sphinx_rtd_theme"
        docs-folder: "src/"
        build-command: "sphinx-build -b html . _build/html"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: src/_build/html/
    - name: Commit documentation changes
      run: |
        git clone https://github.com/solop-develop/docs.git --branch gh-pages --single-branch gh-pages
        cp -r src/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
